<a href="https://colab.research.google.com/github/ravi18kumar2021/numpy-to-viz/blob/main/numpy/dice-roll-simulator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 🎯 Goal:
#### Simulate rolling two dice 10,000 times and count how often each sum (from 2 to 12) appears.

### 🧠 Concepts Used
* np.random.randint
* Element-wise addition
* np.unique with return_counts=True

In [1]:
import numpy as np

In [7]:
arr1 = np.random.randint(1, 7, 10)
arr1

array([2, 2, 2, 4, 4, 2, 3, 1, 2, 2])

In [8]:
arr2 = np.random.randint(1, 7, 10)
arr2

array([5, 1, 3, 5, 3, 2, 1, 5, 1, 2])

In [9]:
sums = arr1 + arr2
sums

array([7, 3, 5, 9, 7, 4, 4, 6, 3, 4])

In [13]:
values, counts = np.unique(sums, return_counts=True)

In [14]:
values

array([3, 4, 5, 6, 7, 9])

In [15]:
counts

array([2, 3, 1, 1, 2, 1])

In [28]:
def roll_dice_simulator(num_rolls):
  arr1 = np.random.randint(1, 7, size=num_rolls)
  arr2 = np.random.randint(1, 7, size=num_rolls)
  sums = arr1 + arr2
  values, counts = np.unique(sums, return_counts=True)
  print(f'After Rolling Dice {num_rolls} times\n')
  for value, count in zip(values, counts):
    print(f"Sum = {value:2} ({count:4} times)")

In [29]:
roll_dice_simulator(10000)

After Rolling Dice 10000 times

Sum =  2 ( 307 times)
Sum =  3 ( 558 times)
Sum =  4 ( 827 times)
Sum =  5 (1110 times)
Sum =  6 (1360 times)
Sum =  7 (1654 times)
Sum =  8 (1397 times)
Sum =  9 (1123 times)
Sum = 10 ( 846 times)
Sum = 11 ( 553 times)
Sum = 12 ( 265 times)
