<a href="https://colab.research.google.com/github/ravi18kumar2021/numpy-to-viz/blob/main/numpy/learning-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing numpy library
import numpy as np

### Creation of an array

In [ ]:
# creating a numpy array from a list
arr = np.array([3, 5, 2, 1, 7])
arr

array([3, 5, 2, 1, 7])

In [ ]:
# creating a n-dimentional numpy array
arr = np.array([[2, 5, 7], [1, 3, 5]])
arr

array([[2, 5, 7],
       [1, 3, 5]])

### Functions to create an array

In [ ]:
# creating an array of zeros
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [ ]:
# creating n-dimensional array of zeros
arr = np.zeros((3, 5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# creating an array of ones
arr = np.ones(7)
arr

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# creating n-dimensional array of ones
arr = np.ones((4, 5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# generate a sequence
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [ ]:
# generate a sequence of custom range
arr = np.arange(3, 10)
arr

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# generate a sequence with custom steps
arr = np.arange(10, 40, 3)
arr

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [ ]:
# generate a sequence with equal spaces between each numbers
arr = np.linspace(3, 4) # default 50 numbers
arr

array([3.        , 3.02040816, 3.04081633, 3.06122449, 3.08163265,
       3.10204082, 3.12244898, 3.14285714, 3.16326531, 3.18367347,
       3.20408163, 3.2244898 , 3.24489796, 3.26530612, 3.28571429,
       3.30612245, 3.32653061, 3.34693878, 3.36734694, 3.3877551 ,
       3.40816327, 3.42857143, 3.44897959, 3.46938776, 3.48979592,
       3.51020408, 3.53061224, 3.55102041, 3.57142857, 3.59183673,
       3.6122449 , 3.63265306, 3.65306122, 3.67346939, 3.69387755,
       3.71428571, 3.73469388, 3.75510204, 3.7755102 , 3.79591837,
       3.81632653, 3.83673469, 3.85714286, 3.87755102, 3.89795918,
       3.91836735, 3.93877551, 3.95918367, 3.97959184, 4.        ])

In [ ]:
# generate a sequence with equal spaces between each numbers
arr = np.linspace(10, 20, 12)
arr

array([10.        , 10.90909091, 11.81818182, 12.72727273, 13.63636364,
       14.54545455, 15.45454545, 16.36363636, 17.27272727, 18.18181818,
       19.09090909, 20.        ])

### Array properties

In [ ]:
# check shape of an array
arr = np.array([[3, 5, 2, 5], [1, 2, 6, 7], [1, 2, 1, 4]])
arr.shape

(3, 4)

In [ ]:
arr = np.array([2, 5, 7, 9, 0])
arr.shape

(5,)

In [ ]:
arr = np.array(7)
arr.shape

()

In [ ]:
# check dimension of an array
arr = np.array([[3, 6, 1], [2, 3, 4]])
arr.ndim

2

In [ ]:
arr = np.array([3, 5, 6])
arr.ndim

1

In [ ]:
arr = np.array(3)
arr.ndim

0

In [ ]:
arr = np.array([3, 5, 9])
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([True, False, False])
arr.dtype

dtype('bool')

In [ ]:
arr = np.array([4.2, 6.8, 1.1])
arr.dtype

dtype('float64')

In [ ]:
arr = np.array(['a', 'b', 'c'])
arr.dtype

dtype('<U1')

### Indexing and Slicing

In [ ]:
# indexing
arr = np.array([2, 6, 3, 9, 1])
arr[3]

np.int64(9)

In [ ]:
arr[0]

np.int64(2)

In [ ]:
arr[-1]

np.int64(1)

In [ ]:
arr = np.array([[2, 1, 4], [4, 3, 6]])
arr[1]

array([4, 3, 6])

In [ ]:
arr[0, 2]

np.int64(4)

In [ ]:
# slicing
arr = np.array([1, 3, 2, 4, 5, 3, 6])
arr[2:4]

array([2, 4])

In [ ]:
arr[0:-1]

array([1, 3, 2, 4, 5, 3])

In [ ]:
arr[5::]

array([3, 6])

In [ ]:
arr[3::-1]

array([[4, 3, 6],
       [2, 1, 4]])

In [ ]:
# reshaping
arr = np.ones(6)
arr.reshape(2, 3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr = np.arange(9)
arr.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Practice Questions - Set 1

In [ ]:
# Q. Create a 1D array of numbers from 0 to 9
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Q. Generate a 3x3 array with all elements as 1
arr = np.ones((3, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Q. Create an array of 10 numbers evenly spaces between 5 and 50
arr = np.linspace(5, 50, 10)
arr

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [ ]:
# Q. Reshape a 1D array of 12 elements into a 3x4 matrix.
arr = np.arange(12)
arr.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Q. Reverse an array using slicing.
arr = np.array([[2, 4, 7], [1, 3, 2], [5, 4, 1], [6, 3, 4]])
arr[::-1]

array([[6, 3, 4],
       [5, 4, 1],
       [1, 3, 2],
       [2, 4, 7]])

### Array Operations

In [ ]:
# element-wise operations
a = np.array([2, 3, 6, 5])
b = np.array([2, 1, 8, 2])
print(f'{a} +  {b} = {a+b}')
print(f'{a} -  {b} = {a-b}')
print(f'{a} x  {b} = {a*b}')
print(f'{a} /  {b} = {a/b}')
print(f'{a} %  {b} = {a%b}')
print(f'{a} // {b} = {a//b}')
print(f'{a} ** {b} = {a**b}')

[2 3 6 5] +  [2 1 8 2] = [ 4  4 14  7]
[2 3 6 5] -  [2 1 8 2] = [ 0  2 -2  3]
[2 3 6 5] x  [2 1 8 2] = [ 4  3 48 10]
[2 3 6 5] /  [2 1 8 2] = [1.   3.   0.75 2.5 ]
[2 3 6 5] %  [2 1 8 2] = [0 0 6 1]
[2 3 6 5] // [2 1 8 2] = [1 3 0 2]
[2 3 6 5] ** [2 1 8 2] = [      4       3 1679616      25]


In [ ]:
# broadcasting
a = np.array([[4, 2, 7], [1, 3, 2]])
b = np.array([2, 3, 5]) # [[2, 3, 5], [2, 3, 5]]
a + b

array([[ 6,  5, 12],
       [ 3,  6,  7]])

In [ ]:
a*b

array([[ 8,  6, 35],
       [ 2,  9, 10]])

In [ ]:
# aggregate function
a

array([[4, 2, 7],
       [1, 3, 2]])

In [ ]:
np.sum(a)

np.int64(19)

In [ ]:
np.average(a)

np.float64(3.1666666666666665)

In [ ]:
np.mean(a)

np.float64(3.1666666666666665)

In [ ]:
np.std(a)

np.float64(1.9507833184532708)

In [ ]:
a

array([[4, 2, 7],
       [1, 3, 2]])

In [ ]:
np.min(a) # overall

np.int64(1)

In [ ]:
np.min(a, axis=0) # column wise

array([1, 2, 2])

In [ ]:
np.min(a, axis=1) # row wise

array([2, 1])

In [ ]:
# logical operations and filtering
b

array([2, 3, 5])

In [ ]:
b > 2

array([False,  True,  True])

In [ ]:
b[b>2]

array([3, 5])

In [ ]:
np.where(b > 2, 'Yes', 'No')

array(['No', 'Yes', 'Yes'], dtype='<U3')

In [ ]:
np.any(b>4)

np.True_

In [ ]:
np.all(b>4)

np.False_

### Practice Questions - Set 2

In [ ]:
# Q. Create two 2D arrays and perform addition, subtraction and multiplication.
a = np.arange(6, 15).reshape(3, 3)
b = np.array([3, 4, 7])

In [ ]:
a

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
b

array([3, 4, 7])

In [ ]:
a + b

array([[ 9, 11, 15],
       [12, 14, 18],
       [15, 17, 21]])

In [ ]:
a - b

array([[3, 3, 1],
       [6, 6, 4],
       [9, 9, 7]])

In [ ]:
a * b

array([[18, 28, 56],
       [27, 40, 77],
       [36, 52, 98]])

In [ ]:
# Q. Given an array, replace all odd numbers with -1.
a

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
np.where(a%2==0, a, -1)

array([[ 6, -1,  8],
       [-1, 10, -1],
       [12, -1, 14]])

In [ ]:
# Q. Filter out all elements greater than a specified value.
a[a > 10]

array([11, 12, 13, 14])

In [ ]:
# generate random integers
np.random.randint(4)

1

In [ ]:
# generate random array
np.random.randint((2, 5))

array([1, 2])

In [ ]:
# generate random 1-dimensional array
np.random.randint(1, 5, 3) # low, high, size

array([2, 2, 4])

In [ ]:
# generate random 2-dimensional array
np.random.randint(3, 8, (2, 3))

array([[7, 6, 4],
       [3, 6, 3]])

In [ ]:
# generate random 2-dimensional array
np.random.randint(2, 9, (2, 3, 2))

array([[[8, 3],
        [6, 2],
        [3, 6]],

       [[5, 5],
        [8, 7],
        [8, 7]]])

In [ ]:
# generate random float values
np.random.rand(5)

array([0.28059075, 0.14787335, 0.43464973, 0.75180564, 0.66024291])

In [ ]:
np.random.rand(3, 4)

array([[0.25603593, 0.07740177, 0.50470094, 0.6584014 ],
       [0.43718528, 0.34483119, 0.83309459, 0.31522498],
       [0.06571979, 0.24750565, 0.04004576, 0.25296869]])

In [ ]:
np.random.seed(18)
np.random.randint(1, 7)

3

In [ ]:
# Q. Create a random 3x3 array of integers between 1 and 20 and find its maximum along axis 0.
arr = np.random.randint(1, 20, (3, 3))
arr

array([[10,  6, 15],
       [ 7, 14,  9],
       [19,  1, 10]])

In [ ]:
np.max(arr, axis=0)

array([19, 14, 15])

### Array Manipulations

In [ ]:
# stacking Arrays
a = np.array([2, 1, 5, 4, 9])
b = np.array([1, 5, 4, 8, 5])

In [ ]:
np.hstack((a, b))

array([2, 1, 5, 4, 9, 1, 5, 4, 8, 5])

In [ ]:
np.hstack((b, a))

array([1, 5, 4, 8, 5, 2, 1, 5, 4, 9])

In [ ]:
np.vstack((a, b))

array([[2, 1, 5, 4, 9],
       [1, 5, 4, 8, 5]])

In [ ]:
np.vstack((b, a))

array([[1, 5, 4, 8, 5],
       [2, 1, 5, 4, 9]])

In [ ]:
np.concatenate((a, b))

array([2, 1, 5, 4, 9, 1, 5, 4, 8, 5])

In [ ]:
np.concatenate((a, b), axis=0)

array([2, 1, 5, 4, 9, 1, 5, 4, 8, 5])

In [ ]:
np.concatenate((b, a), axis=0)

array([1, 5, 4, 8, 5, 2, 1, 5, 4, 9])

In [ ]:
a = np.random.randint(1, 10, (3, 4))
b = np.random.randint(3, 15, (4, 4))

In [ ]:
a

array([[4, 5, 8, 5],
       [4, 2, 2, 8],
       [7, 6, 9, 4]])

In [ ]:
b

array([[ 6,  5, 13,  5],
       [10, 13,  6,  8],
       [12,  5, 12, 12],
       [ 7,  8, 11, 10]])

In [ ]:
np.vstack((a, b)) # hstack is not possible for (3x4 and 4x4)

array([[ 4,  5,  8,  5],
       [ 4,  2,  2,  8],
       [ 7,  6,  9,  4],
       [ 6,  5, 13,  5],
       [10, 13,  6,  8],
       [12,  5, 12, 12],
       [ 7,  8, 11, 10]])

In [ ]:
np.vstack((b, a))

array([[ 6,  5, 13,  5],
       [10, 13,  6,  8],
       [12,  5, 12, 12],
       [ 7,  8, 11, 10],
       [ 4,  5,  8,  5],
       [ 4,  2,  2,  8],
       [ 7,  6,  9,  4]])

In [ ]:
np.concatenate((a, b)) # axis=0 acts as vertical stacking

array([[ 4,  5,  8,  5],
       [ 4,  2,  2,  8],
       [ 7,  6,  9,  4],
       [ 6,  5, 13,  5],
       [10, 13,  6,  8],
       [12,  5, 12, 12],
       [ 7,  8, 11, 10]])

In [ ]:
np.concatenate((b, a))

array([[ 6,  5, 13,  5],
       [10, 13,  6,  8],
       [12,  5, 12, 12],
       [ 7,  8, 11, 10],
       [ 4,  5,  8,  5],
       [ 4,  2,  2,  8],
       [ 7,  6,  9,  4]])

In [ ]:
a = np.random.randn(3, 5)
b = np.random.randn(3, 4)

In [ ]:
a

array([[ 0.56575119,  0.28626894, -1.38784273, -1.4248273 ,  1.43803841],
       [-0.76801552,  0.29456934,  1.61256273, -1.08758565, -0.39065691],
       [ 0.06925078,  0.7018503 , -0.63168317,  0.58896785,  0.27162015]])

In [ ]:
b

array([[ 1.35927347,  0.85479387, -0.1190375 , -0.61079705],
       [ 0.60562302,  0.94143676,  2.0609693 ,  2.19073607],
       [-0.605557  , -1.46762056,  2.2305251 ,  0.02748521]])

In [ ]:
np.hstack((a, b)) # vstack is not possible for (3x4 and 3x5)

array([[ 0.56575119,  0.28626894, -1.38784273, -1.4248273 ,  1.43803841,
         1.35927347,  0.85479387, -0.1190375 , -0.61079705],
       [-0.76801552,  0.29456934,  1.61256273, -1.08758565, -0.39065691,
         0.60562302,  0.94143676,  2.0609693 ,  2.19073607],
       [ 0.06925078,  0.7018503 , -0.63168317,  0.58896785,  0.27162015,
        -0.605557  , -1.46762056,  2.2305251 ,  0.02748521]])

In [ ]:
np.concatenate((a, b), axis=1) # axis=1 acts as horizontal stacking

array([[ 0.56575119,  0.28626894, -1.38784273, -1.4248273 ,  1.43803841,
         1.35927347,  0.85479387, -0.1190375 , -0.61079705],
       [-0.76801552,  0.29456934,  1.61256273, -1.08758565, -0.39065691,
         0.60562302,  0.94143676,  2.0609693 ,  2.19073607],
       [ 0.06925078,  0.7018503 , -0.63168317,  0.58896785,  0.27162015,
        -0.605557  , -1.46762056,  2.2305251 ,  0.02748521]])

In [ ]:
# splitting of an array
arr = np.arange(3, 15, 2)
arr

array([ 3,  5,  7,  9, 11, 13])

In [ ]:
# splitting of 1D array
np.split(arr, 2)

[array([3, 5, 7]), array([ 9, 11, 13])]

In [ ]:
np.split(arr, 3)

[array([3, 5]), array([7, 9]), array([11, 13])]

In [ ]:
arr = np.arange(2, 27, 3).reshape(3, 3)
arr

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [ ]:
# splitting of 2D array
np.split(arr, 3)

[array([[2, 5, 8]]), array([[11, 14, 17]]), array([[20, 23, 26]])]

In [ ]:
np.split(arr, 3, axis=0) # 3 splits in 3 rows

[array([[2, 5, 8]]), array([[11, 14, 17]]), array([[20, 23, 26]])]

In [ ]:
np.split(arr, 3, axis=1) # 3 splits in 3 columns

[array([[ 2],
        [11],
        [20]]),
 array([[ 5],
        [14],
        [23]]),
 array([[ 8],
        [17],
        [26]])]

In [ ]:
np.split(arr, 1) # 1 is default value

[array([[ 2,  5,  8],
        [11, 14, 17],
        [20, 23, 26]])]

In [ ]:
# hsplit on 1D array
arr = np.arange(3, 20, 2)
arr

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.hsplit(arr, 3) # vsplit is not valid for 1D array

[array([3, 5, 7]), array([ 9, 11, 13]), array([15, 17, 19])]

In [ ]:
# hsplit
arr = np.arange(3, 26, 2).reshape(3, 4)
arr

array([[ 3,  5,  7,  9],
       [11, 13, 15, 17],
       [19, 21, 23, 25]])

In [ ]:
np.hsplit(arr, 1)

[array([[ 3,  5,  7,  9],
        [11, 13, 15, 17],
        [19, 21, 23, 25]])]

In [ ]:
np.hsplit(arr, 2)

[array([[ 3,  5],
        [11, 13],
        [19, 21]]),
 array([[ 7,  9],
        [15, 17],
        [23, 25]])]

In [ ]:
np.hsplit(arr, 4)

[array([[ 3],
        [11],
        [19]]),
 array([[ 5],
        [13],
        [21]]),
 array([[ 7],
        [15],
        [23]]),
 array([[ 9],
        [17],
        [25]])]

In [ ]:
np.vsplit(arr, 1) # same as hsplit 1

[array([[ 3,  5,  7,  9],
        [11, 13, 15, 17],
        [19, 21, 23, 25]])]

In [ ]:
np.vsplit(arr, 3)

[array([[3, 5, 7, 9]]), array([[11, 13, 15, 17]]), array([[19, 21, 23, 25]])]

In [ ]:
# sorting of an array
arr = np.random.randint(1, 15, 10)
arr

array([ 5,  3, 13, 14,  7,  4,  8,  9, 14,  4])

In [ ]:
np.sort(arr)

array([ 3,  4,  4,  5,  7,  8,  9, 13, 14, 14])

In [ ]:
arr = np.random.randint(1, 10, (3, 4))
arr

array([[1, 9, 3, 4],
       [6, 1, 2, 8],
       [4, 7, 1, 5]])

In [ ]:
np.sort(arr) # axis=1

array([[1, 3, 4, 9],
       [1, 2, 6, 8],
       [1, 4, 5, 7]])

In [ ]:
np.sort(arr, axis=0)

array([[1, 1, 1, 4],
       [4, 7, 2, 5],
       [6, 9, 3, 8]])

In [ ]:
# unique elements
arr = np.random.randint(1, 9, 10)
arr

array([1, 6, 6, 6, 5, 5, 3, 8, 6, 5])

In [ ]:
np.unique(arr)

array([1, 3, 5, 6, 8])

In [ ]:
np.unique(arr, return_counts=True) # counts of each unique elements

(array([1, 3, 5, 6, 8]), array([1, 1, 3, 4, 1]))

In [ ]:
np.unique(arr, return_index=True) # indexes of first appearance of each unique elements

(array([1, 3, 5, 6, 8]), array([0, 6, 4, 1, 7]))

In [ ]:
np.unique(arr, return_inverse=True) # indexes of elements in ascending order

(array([1, 3, 5, 6, 8]), array([0, 3, 3, 3, 2, 2, 1, 4, 3, 2]))

In [2]:
# set operations
a = np.random.randint(1, 10, 6)
b = np.random.randint(3, 9, 5)

In [3]:
a

array([5, 4, 1, 8, 7, 4])

In [4]:
b

array([7, 3, 7, 8, 5])

In [5]:
np.intersect1d(a, b)

array([5, 7, 8])

In [6]:
np.union1d(a, b)

array([1, 3, 4, 5, 7, 8])

In [7]:
np.setdiff1d(a, b)

array([1, 4])

In [8]:
np.setdiff1d(b, a)

array([3])

### Practice Questions - Set 3

In [9]:
# Q. Stack two arrays horizontally and vertically.
a = np.array([3, 5, 1, 4])
b = np.array([1, 9, 5, 2])

In [11]:
np.hstack((a, b))

array([3, 5, 1, 4, 1, 9, 5, 2])

In [12]:
np.vstack((b, a))

array([[1, 9, 5, 2],
       [3, 5, 1, 4]])

In [20]:
# Q. Sort a 2D array along the rows.
arr = np.array([[5, 2, 7, 6], [7, 2, 4, 3], [1, 5, 8, 3]])
arr

array([[5, 2, 7, 6],
       [7, 2, 4, 3],
       [1, 5, 8, 3]])

In [21]:
np.sort(arr) # along rows

array([[2, 5, 6, 7],
       [2, 3, 4, 7],
       [1, 3, 5, 8]])

In [22]:
np.sort(arr, axis=0) # along columns

array([[1, 2, 4, 3],
       [5, 2, 7, 3],
       [7, 5, 8, 6]])

In [26]:
# Q. Find the unique elements in an array and their counts.
arr = np.random.randint(4, 15, 10)
arr

array([11, 13,  9, 14, 14,  6, 11,  9, 11, 14])

In [27]:
np.unique(arr)

array([ 6,  9, 11, 13, 14])

In [28]:
np.unique(arr, return_counts=True)

(array([ 6,  9, 11, 13, 14]), array([1, 2, 3, 1, 3]))

In [29]:
# Q. Given two arrays, find the elements common to both.
a = np.random.randint(5, 10, 8)
b = np.random.randint(1, 8, 10)

In [30]:
a

array([8, 7, 5, 7, 7, 9, 7, 9])

In [31]:
b

array([5, 1, 1, 5, 6, 6, 7, 7, 5, 4])

In [32]:
np.intersect1d(a, b)

array([5, 7])

### Statistics

In [38]:
# Normal Distribution
arr = np.random.normal(loc=0, scale=1, size=5) # mean=0, std=1
arr

array([-0.20472009,  1.18651188, -1.54273073,  0.5644497 , -0.8334243 ])

In [47]:
arr = np.random.normal(loc=1, scale=3, size=(3, 4))
arr

array([[ 1.19079651,  0.11420846, -0.66434   ,  1.31143847],
       [-1.33269724,  3.28367745, -0.81119805,  2.88541798],
       [-0.51501423, -3.31540098,  3.47388056,  2.90104468]])

In [48]:
# Uniform Distribution
arr = np.random.uniform(low=0, high=5, size=4)
arr

array([4.07593175, 2.38998399, 1.90690744, 2.47481624])

In [49]:
arr = np.random.uniform(low=5, high=10, size=(3, 3))
arr

array([[7.41129118, 6.19825652, 8.28534036],
       [8.72918016, 6.94006096, 9.3080767 ],
       [6.83437367, 7.02891341, 6.47663745]])

In [55]:
# mean, median, std, var
arr = np.random.randint(1, 5, 10)
arr

array([2, 1, 3, 1, 4, 2, 2, 1, 4, 2])

In [56]:
np.mean(arr)

np.float64(2.2)

In [57]:
np.median(arr)

np.float64(2.0)

In [58]:
np.std(arr)

np.float64(1.0770329614269007)

In [59]:
np.var(arr)

np.float64(1.16)

In [62]:
# correlation coefficient
a = np.array([2, 5, 8, 10])
b = np.array([1, 4, 5, 6])
np.corrcoef(a, b)

array([[1.        , 0.96990677],
       [0.96990677, 1.        ]])

In [66]:
a = np.array([[3, 5, 6], [2, 4, 5]])
b = np.array([[2, 3, 7], [1, 7, 3]])

In [67]:
a

array([[3, 5, 6],
       [2, 4, 5]])

In [68]:
b

array([[2, 3, 7],
       [1, 7, 3]])

In [69]:
np.corrcoef(a, b)

array([[1.       , 1.       , 0.8660254, 0.5      ],
       [1.       , 1.       , 0.8660254, 0.5      ],
       [0.8660254, 0.8660254, 1.       , 0.       ],
       [0.5      , 0.5      , 0.       , 1.       ]])

### Practice Question - Set 4

In [75]:
# Q. Generate a 5x5 array of random numbers between 0 and 1.
np.random.rand(5, 5)

array([[0.85751828, 0.02758542, 0.27157651, 0.08749186, 0.13812734],
       [0.68599667, 0.93880691, 0.60172146, 0.06622806, 0.37023434],
       [0.66066593, 0.90527992, 0.33896586, 0.79703202, 0.69883391],
       [0.77899597, 0.84647151, 0.03402184, 0.50424281, 0.8588003 ],
       [0.78719017, 0.46287127, 0.60235898, 0.75009364, 0.71761055]])

In [85]:
# Q. Set a seed and generate the same random array twice.
np.random.seed(18)
np.random.rand()

0.6503742417395917

In [86]:
np.random.seed(18)
np.random.rand()

0.6503742417395917

In [90]:
# Q. Generate an array of 1000 random numbers and calculate mean and standard deviation.
arr = np.random.randint(1, 100, 1000)
arr

array([95,  6, 15, 63,  1, 35, 81, 93, 37, 84, 42, 52, 96, 82, 78, 37, 27,
        2, 57, 13, 89, 78, 23, 41, 86,  2, 81, 49, 27, 84, 40, 91, 52, 21,
       99,  8, 50, 95, 80, 28, 37, 54, 49,  7, 33, 95, 68, 87, 13, 49, 63,
       31, 89, 18, 83, 47, 91, 79, 79, 93, 78, 23, 17, 51, 77, 41, 19, 49,
       10, 97, 32, 17,  4, 79, 50, 58, 82, 47, 15, 36, 24, 18,  4, 22, 43,
       74, 34,  4, 95,  2, 76, 32, 24, 94, 45, 15, 90, 39, 86, 11, 76, 40,
       94, 18, 17, 64,  5, 63, 54, 42, 40, 76, 84, 96, 31, 88,  7, 77, 66,
       80, 14, 44, 53, 67, 23, 82, 60,  7, 81, 28, 76, 50, 99, 51, 21, 66,
       86, 87, 37, 39, 29, 72, 49, 58, 18,  4, 51, 76, 61,  5, 26, 37, 98,
       21, 49, 76, 92, 92, 20, 17, 30, 80, 30, 20, 55, 76,  8, 54, 82, 27,
       15, 63, 52, 42, 65, 25, 71, 21, 43, 74, 52, 15, 14,  6, 13, 15, 64,
       56, 70, 51, 50, 29, 51, 56, 69, 48,  5, 29, 74, 27,  9, 75,  3, 32,
       76, 67, 15, 48, 57, 92, 81, 80, 96, 77, 66, 74, 66, 59, 12, 89, 38,
       75,  6, 67, 61, 13

In [91]:
np.mean(arr)

np.float64(50.742)

In [92]:
np.std(arr)

np.float64(28.87610493124029)

In [97]:
# Q. Create two arrays of 100 elements from normal distributions (mean=0, std=1)
# and compute their correlation coefficient.
a = np.random.normal(loc=0, scale=1, size=100)
b = np.random.normal(loc=0, scale=1, size=100)

In [98]:
np.corrcoef(a, b)

array([[1.        , 0.23677887],
       [0.23677887, 1.        ]])

### Linear Algebra

In [103]:
a = np.array([[2, 5], [1, 4]])
a

array([[2, 5],
       [1, 4]])

In [104]:
b = np.array([[6, 5], [2, 9]])
b

array([[6, 5],
       [2, 9]])

In [105]:
# element wise operation
a * b

array([[12, 25],
       [ 2, 36]])

In [106]:
# dot product
np.dot(a, b)

array([[22, 55],
       [14, 41]])

In [107]:
a @ b

array([[22, 55],
       [14, 41]])

In [109]:
np.dot(b, a)

array([[17, 50],
       [13, 46]])

In [108]:
b @ a

array([[17, 50],
       [13, 46]])

In [110]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [111]:
np.eye(2, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [114]:
# determinant of a matrix
a = np.array([[1, 4], [5, 4]])
np.linalg.det(a)

np.float64(-15.999999999999998)

In [115]:
# inverse of a matrix
np.linalg.inv(a)

array([[-0.25  ,  0.25  ],
       [ 0.3125, -0.0625]])

In [118]:
# eigen values and eigen vectors
value, vector = np.linalg.eig(a)

In [119]:
value

array([-2.21699057,  7.21699057])

In [120]:
vector

array([[-0.77925158, -0.54107946],
       [ 0.62671124, -0.84097147]])

In [123]:
# solving linear equations (Ax = b)
# 2x + y = 8, x + 3y = 13
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])
np.linalg.solve(A, b)

array([2.2, 3.6])

In [124]:
# 3x + y = 9, x + 2y = 8
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
np.linalg.solve(A, b)

array([2., 3.])

In [126]:
# x + y + z = 6, 2x + 5y + z = -4, 2x + 3y + 8z = 27
A = np.array([[1, 1, 1], [2, 5, 1], [2, 3, 8]])
b = np.array([6, -4, 27])
np.linalg.solve(A, b)

array([ 7.05263158, -4.26315789,  3.21052632])

### Practice Quesions - Set 5

In [127]:
# Q. Multiply two matrices (2×2 or 3×3)
a = np.array([[3, 2, 5], [6, 1, 7]])
a

array([[3, 2, 5],
       [6, 1, 7]])

In [128]:
b = np.array([[4, 3], [1, 5], [7, 5]])
b

array([[4, 3],
       [1, 5],
       [7, 5]])

In [130]:
np.dot(a, b)

array([[49, 44],
       [74, 58]])

In [131]:
a @ b

array([[49, 44],
       [74, 58]])

In [135]:
# Q. Find the determinant and inverse of a 2×2 matrix.
arr = np.random.randint(1, 5, size=(2, 2))
arr

array([[4, 2],
       [3, 3]])

In [136]:
np.linalg.det(arr)

np.float64(6.0)

In [137]:
np.linalg.inv(arr)

array([[ 0.5       , -0.33333333],
       [-0.5       ,  0.66666667]])

In [138]:
# Q. Find the eigenvalues and eigenvectors of a 2×2 matrix.
values, vectors = np.linalg.eig(arr)

In [139]:
values

array([6., 1.])

In [140]:
vectors

array([[ 0.70710678, -0.5547002 ],
       [ 0.70710678,  0.83205029]])

In [141]:
# Q. Solve the following system of equations using np.linalg.solve: 2x + y = 8, x + 3y = 13
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])
np.linalg.solve(A, b)

array([2.2, 3.6])