<a href="https://colab.research.google.com/github/ravi18kumar2021/numpy-to-viz/blob/main/numpy/marksheet-analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 🎯 Goal:
### Given a 2D NumPy array where each row represents a student and each column a subject, perform common marks analysis.

### Concepts Used

- Array slicing
- axis parameter in NumPy functions
- np.sum, np.mean, np.argmax, np.min, etc.

In [46]:
import numpy as np

In [47]:
# 5 students, 4 subjects
marks = np.random.randint(40, 101, size=(5, 4))
marks

array([[56, 87, 65, 62],
       [69, 89, 92, 58],
       [70, 70, 52, 90],
       [52, 78, 74, 51],
       [70, 50, 92, 81]])

In [48]:
# Q. Calculate total marks per student
for index, mark in enumerate(marks):
  print(f'Total Marks of Student {index + 1} : {np.sum(mark)}')

Total Marks of Student 1 : 270
Total Marks of Student 2 : 308
Total Marks of Student 3 : 282
Total Marks of Student 4 : 255
Total Marks of Student 5 : 293


In [49]:
np.sum(marks, axis=1) # row wise

array([270, 308, 282, 255, 293])

In [50]:
# Q. Find average marks per subject
for i in range(4):
  print(f'Average Marks of Subject {i+1} : {np.mean(marks[:, i])}')

Average Marks of Subject 1 : 63.4
Average Marks of Subject 2 : 74.8
Average Marks of Subject 3 : 75.0
Average Marks of Subject 4 : 68.4


In [51]:
np.mean(marks, axis=0)

array([63.4, 74.8, 75. , 68.4])

In [52]:
# Q. Identify top and bottom scoring students
for index, student in enumerate(np.argmax(marks, axis=0)):
  print(f'Subject {index+1} Top Scorer : Student {student+1}')

Subject 1 Top Scorer : Student 3
Subject 2 Top Scorer : Student 2
Subject 3 Top Scorer : Student 2
Subject 4 Top Scorer : Student 3


In [53]:
for index, student in enumerate(np.argmin(marks, axis=0)):
  print(f'Subject {index+1} Bottom Scorer : Student {student+1}')

Subject 1 Bottom Scorer : Student 4
Subject 2 Bottom Scorer : Student 5
Subject 3 Bottom Scorer : Student 3
Subject 4 Bottom Scorer : Student 4


In [54]:
# Q. Rank all students by total score
for index in np.argsort(np.sum(marks, axis=1))[::-1]:
  print(f'Marks of Student {index+1} : {np.sum(marks[index])}')

Marks of Student 2 : 308
Marks of Student 5 : 293
Marks of Student 3 : 282
Marks of Student 1 : 270
Marks of Student 4 : 255
